
# Change to 8.0
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /source

COPY *.csproj .
COPY *.config .
RUN dotnet restore

COPY . .
RUN dotnet publish -c release --no-restore -o /app


# Change to 8.0
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app ./
ENTRYPOINT ["dotnet", "releasesapi.dll"]

# docker images test: 250 MB
