
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /source

COPY *.csproj .
COPY *.config .
RUN dotnet restore

COPY . .
RUN dotnet publish -c release --no-restore -o /app


FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app ./

# Add user:
# 1654 or "app"
USER $APP_UID

ENTRYPOINT ["dotnet", "releasesapi.dll"]
